### ISSUE TITLE
Gutter sign render issue

### ISSUE THREAD

**Issue by everdimension** [yunlingz/ci_dark#1]
Hi!

I'm using vim-signify for highlighting changed lines in the gutter. Vim-signify settings:
```
let g:signify_sign_add = '▏'
let g:signify_sign_change = '▏'
```

<details>
<summary>It's expected to look like this (one-dark theme)</summary>

![image](https://user-images.githubusercontent.com/5347023/89774207-1f565c80-db0e-11ea-9c58-f5a78a4c6a06.png)
</details>

<details>
<summary>But with this theme is looks like this:</summary>

![image](https://user-images.githubusercontent.com/5347023/89774127-eae2a080-db0d-11ea-93cf-a9d356c2d202.png)
</details>

Also notice how the "warning circle" is displayed in green with your theme, but expected to be yellow.

**Comment by yunlingz** [comment]
It should have been fixed in the latest commit, please update theme to the latest version.

**Comment by everdimension** [comment]
Great, thanks!
