### ISSUE TITLE
Important: for users who found problem while updating this repo by plugin manager such as vim-plug, here is the solution.

### ISSUE THREAD

**Issue by jemag** [yunlingz/ci_dark#2]
Since this is meant to be a theme used by others, re-writing the commit history of the master branch is a bad practice that impacts:
1. Any individuals using your repository
2. Individuals using your theme within vim/nvim with a plugin manager. Several plugin managers use git to manage plugins, therefore when re-writing the commit history of the master branch, this will cause errors trying to update your plugin

In general, with git, it is better to never alter the history of commits once it has been pushed, since it can then impact other users.

**Comment by yunlingz** [comment]
For users who found problem while updating this theme by plugin manager such as vim-plug:

To solve this problem (for `vim-plug` users), first run `PlugClean` to detect the problem and delete the directory, then re-run `PlugUpdate` or `PlugInstall`.

**Comment by yunlingz** [comment]
> Since this is meant to be a theme used by others, re-writing the commit history of the master branch is a bad practice that impacts:
> 
> 1. Any individuals using your repository
> 2. Individuals using your theme within vim/nvim with a plugin manager. Several plugin managers use git to manage plugins, therefore when re-writing the commit history of the master branch, this will cause errors trying to update your plugin
> 
> In general, with git, it is better to never alter the history of commits once it has been pushed, since it can then impact other users.

Thanks for your suggestions, I will be more careful while editing local branches. Sorry for the inconvenience.
